/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dummy } from "./Dummy";
export * as factories from "./factories";
export { Dummy__factory } from "./factories/Dummy__factory";
